name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Anvil Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Build & install CLI
        run: cargo install --path . --force
      - name: Run Anvil
        run: anvil &
      - name: Run integration tests
        env:
          RPC_URL: http://localhost:8545
        run: cargo test --test cli_integration -- --show-output --ignored
