name: Integration Tests

on:
  workflow_dispatch:
  # push:
    # branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Anvil & Testnet Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run integration tests
        env:
          RPC_URL: http://localhost:8545
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: cargo test -- --ignored
      - name: Optional Testnet Run
        if: success()
        env:
          RPC_URL: ${{ secrets.TESTNET_RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: cargo run --release -- testnet-send
